// templates.js — shipped defaults (edit/track in git). The app reads this first,
// then lets users override via Templates tab (saved to localStorage).
window.KG_DEFAULT_TEMPLATES = {
  "types": {
  "Type 1": {
    "columns": ["Campaign Name", "Adset Name", "Keywords"],
    "searchRows": [
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}","keywords":"{BUILDER + PROJECT}"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}","keywords":"{BUILDER + PROJECT} {LOCATION}"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_bhk","keywords":"{BUILDER + PROJECT} {TYPOLOGY 1}"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_bhk","keywords":"{BUILDER + PROJECT} {TYPOLOGY 2}"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_bhk","keywords":"{BUILDER + PROJECT} {TYPOLOGY 3}"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_bhk","keywords":"{BUILDER + PROJECT} {TYPOLOGY 4}"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_bhk","keywords":"{BUILDER + PROJECT} {TYPOLOGY 5}"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_bhk","keywords":"{BUILDER + PROJECT} {TYPOLOGY 6}"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_amenities","keywords":"{BUILDER + PROJECT} amenities"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_best_offers","keywords":"{BUILDER + PROJECT} best offers"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_booking","keywords":"{BUILDER + PROJECT} booking"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_construction_status","keywords":"{BUILDER + PROJECT} construction status"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_floor_plan","keywords":"{BUILDER + PROJECT} floor plan"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_launch_price","keywords":"{BUILDER + PROJECT} launch price"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_launch_date","keywords":"{BUILDER + PROJECT} launch date"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_location","keywords":"{BUILDER + PROJECT} location"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_master_plan","keywords":"{BUILDER + PROJECT} master plan"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_payment_plan","keywords":"{BUILDER + PROJECT} payment plan"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_possession_date","keywords":"{BUILDER + PROJECT} possession date"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_price","keywords":"{BUILDER + PROJECT} price"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_rera_number","keywords":"{BUILDER + PROJECT} rera number"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_reviews","keywords":"{BUILDER + PROJECT} reviews"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_site_visit","keywords":"{BUILDER + PROJECT} site visit"},
      {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_specifications","keywords":"{BUILDER + PROJECT} specifications"}
    ],
    "adsColumns": ["Particulars", "Ads Copy"],
    "adsRows": [
      {"particular":"H1 - Project Name","copy":"{BUILDER + PROJECT}"},
      {"particular":"H1 - Location","copy":"{BUILDER + PROJECT} {LOCATION}"},
      {"particular":"H1 - Project type","copy":"{TYPOLOGY 1}/{TYPOLOGY 2}/{TYPOLOGY 3}/{TYPOLOGY 4}/{TYPOLOGY 5}/{TYPOLOGY 6} BHK Apartments"},
      {"particular":"H1","copy":"{PROJECT} {LOCATION}"},
      {"particular":"1 - Project + Luxury + Type","copy":"Luxe {TYPOLOGY 1}/{TYPOLOGY 2}/{TYPOLOGY 3}/{TYPOLOGY 4}/{TYPOLOGY 5}/{TYPOLOGY 6} BHK Apartments"},
      {"particular":"1 - Project + Location + City","copy":"{PROJECT} {CITY}"},
      {"particular":"2 - Price Range","copy":"Price {PRICE RANGE}"},
      {"particular":"2 - Starting Price","copy":"Price Starts {PRICE}"},
      {"particular":"2 - Type & Starting Price","copy":"{TYPOLOGY 1}/{TYPOLOGY 2}/{TYPOLOGY 3}/{TYPOLOGY 4}/{TYPOLOGY 5}/{TYPOLOGY 6} BHK Starts {PRICE}"},
      {"particular":"H3","copy":"Lock Price Now!"},
      {"particular":"H3","copy":"Exclusive Deal"},
      {"particular":"H3","copy":"Filling Fast"},
      {"particular":"H3","copy":"Hold Price"},
      {"particular":"H3","copy":"Limited Units"},
      {"particular":"H3","copy":"Experience A Modern Living"},
      {"particular":"H3","copy":"Avail Pre-Launch Offers"},
      {"particular":"H3","copy":"Get In Touch With Us"},
      {"particular":"H3","copy":"View Prices, Deals & Offers"},
      {"particular":"H3","copy":"Pre-Launch Offers Live Now"},
      {"particular":"H3","copy":"Get Instant Call Back"},
      {"particular":"H3","copy":"{PRICE} Lock Price Now!"},
      {"particular":"H3","copy":"Live Grand in {CITY}"},
      {"particular":"Description 1 (A)","copy":"{BUILDER + PROJECT} - Luxe Apartments From {PRICE} . Lock Price Now! Limited Units"},
      {"particular":"Description 1 (B)","copy":"{PROJECT} {CITY} {TYPOLOGY 1} starts {PRICE}*. Exclusive Deal! Filling Fast."},
      {"particular":"Description 2 (A)","copy":"Book Your Dream Today - Premium Living Awaits!"},
      {"particular":"Description 2 (B)","copy":"Luxury in Prime Location - Schedule a Site Visit Now!"},
      {"particular":"Description 3","copy":"{PROJECT} Offers {TYPOLOGY 1} {TYPOLOGY 2} Flats in {ROAD} Project Starting From {PRICE} Onwards"},
      {"particular":"Description 4","copy":"{BUILDER + PROJECT}: Modern Design, Premium Amenities & Prime Location for Elevated Living"},
      {"particular":"Description 5","copy":"{BUILDER + PROJECT} - for Greener View, Greater Connectivity & Worldclass Amenities"},
      {"particular":"Description 6","copy":"This Project Embodies Modern Urban Living, Offering Residents a Blend of Comfort and Convenience"},
      {"particular":"Description 7","copy":"{BUILDER + PROJECT} is a Proposed Luxury Residential Development on {ROAD} in "},
      {"particular":"Description 8","copy":""},
      {"particular":"Description 9","copy":""},
      {"particular":"Description 10","copy":""},
      {"particular":"Description 11","copy":""},
      {"particular":"Description 12","copy":""},
      {"particular":"Description 13","copy":""},
      {"particular":"Description 14","copy":""},
      {"particular":"Description 15","copy":""},
      {"particular":"Description 16","copy":""},
      {"particular":"Description 17","copy":""},
      {"particular":"Description 18","copy":""},
      {"particular":"Description 19","copy":""},
      {"particular":"Description 20","copy":""},
      {"particular":"Description 21","copy":""},
      {"particular":"Description 22","copy":""},
      {"particular":"Description 23","copy":""},
      {"particular":"Description 24","copy":""},
      {"particular":"Description 25","copy":""},
      {"particular":"Description 26","copy":""},
      {"particular":"Description 27","copy":""},
      {"particular":"Description 28","copy":""},
      {"particular":"Description 29","copy":""},
      {"particular":"Description 30","copy":""}
    ],
    "variables": [
      "{BUILDER + PROJECT}",
      "{LOCATION}",
      "{TYPOLOGY 1}",
      "{TYPOLOGY 2}",
      "{TYPOLOGY 3}",
      "{TYPOLOGY 4}",
      "{TYPOLOGY 5}",
      "{TYPOLOGY 6}",
      "{PROJECT}",
      "{CITY}",
      "{PRICE}",
      "{PRICE RANGE}",
      "{ROAD}"
    ]
  }
}

}
