// templates.js — shipped defaults (tracked in git). The app reads this first,
// then lets users override via Templates tab (saved to localStorage).
window.KG_DEFAULT_TEMPLATES = {
  "types": {
    "Type 1": {
      "nickname": "Brand - Apartment",
      "columns": ["Campaign Name", "Adset Name", "Keywords"],
      "searchRows": [
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}","keywords":"{BUILDER + PROJECT}"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}","keywords":"{BUILDER + PROJECT} {LOCATION}"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_bhk","keywords":"{BUILDER + PROJECT} {TYPOLOGY 1} bhk"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_bhk","keywords":"{BUILDER + PROJECT} {TYPOLOGY 2} bhk"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_bhk","keywords":"{BUILDER + PROJECT} {TYPOLOGY 3} bhk"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_bhk","keywords":"{BUILDER + PROJECT} {TYPOLOGY 4} bhk"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_bhk","keywords":"{BUILDER + PROJECT} {TYPOLOGY 5} bhk"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_bhk","keywords":"{BUILDER + PROJECT} {TYPOLOGY 6} bhk"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_amenities","keywords":"{BUILDER + PROJECT} amenities"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_best_offers","keywords":"{BUILDER + PROJECT} best offers"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_booking","keywords":"{BUILDER + PROJECT} booking"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_construction_status","keywords":"{BUILDER + PROJECT} construction status"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_floor_plan","keywords":"{BUILDER + PROJECT} floor plan"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_launch_price","keywords":"{BUILDER + PROJECT} launch price"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_launch_date","keywords":"{BUILDER + PROJECT} launch date"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_location","keywords":"{BUILDER + PROJECT} location"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_master_plan","keywords":"{BUILDER + PROJECT} master plan"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_payment_plan","keywords":"{BUILDER + PROJECT} payment plan"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_possession_date","keywords":"{BUILDER + PROJECT} possession date"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_price","keywords":"{BUILDER + PROJECT} price"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_rera_number","keywords":"{BUILDER + PROJECT} rera number"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_reviews","keywords":"{BUILDER + PROJECT} reviews"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_site_visit","keywords":"{BUILDER + PROJECT} site visit"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_specifications","keywords":"{BUILDER + PROJECT} specifications"}
      ],
      "adsColumns": ["Particulars", "Ads Copy"],
      "adsRows": [
        {"particular":"H1 - Project Name","copy":"{BUILDER + PROJECT}","section":"heading"},
        {"particular":"H1 - Location","copy":"{BUILDER + PROJECT} {LOCATION}","section":"heading"},
        {"particular":"H1 - Project type","copy":"{JOIN:TYPOLOGY 1, TYPOLOGY 2, TYPOLOGY 3, TYPOLOGY 4, TYPOLOGY 5, TYPOLOGY 6} BHK Apartments","section":"heading","X": true},
        {"particular":"H1 - Project + Location","copy":"{PROJECT} {LOCATION}","section":"heading"},
        {"particular":"1 - Project + Luxury + Type","copy":"Luxe {JOIN:TYPOLOGY 1, TYPOLOGY 2, TYPOLOGY 3, TYPOLOGY 4, TYPOLOGY 5, TYPOLOGY 6} BHK Apartments","section":"heading","X": true},
        {"particular":"1 - Project + Location + City","copy":"{PROJECT} {CITY}","section":"heading"},
        {"particular":"2 - Price Range","copy":"Price {PRICE RANGE}","section":"heading"},
        {"particular":"2 - Starting Price","copy":"Price Starts {PRICE}","section":"heading"},
        {"particular":"2 - Type & Starting Price","copy":"{TYPOLOGY 1} BHK Starts {PRICE}","section":"heading"},
        {"particular":"H3","copy":"Lock Price Now!","section":"heading"},
        {"particular":"H3","copy":"Exclusive Deal","section":"heading"},
        {"particular":"H3","copy":"Filling Fast","section":"heading"},
        {"particular":"H3","copy":"Hold Price","section":"heading"},
        {"particular":"H3","copy":"Limited Units","section":"heading"},
        {"particular":"H3","copy":"Experience A Modern Living","section":"heading"},
        {"particular":"H3","copy":"Avail Pre-Launch Offers","section":"heading"},
        {"particular":"H3","copy":"Get In Touch With Us","section":"heading"},
        {"particular":"H3","copy":"View Prices, Deals & Offers","section":"heading"},
        {"particular":"H3","copy":"Pre-Launch Offers Live Now","section":"heading"},
        {"particular":"H3","copy":"Get Instant Call Back","section":"heading"},
        {"particular":"H3","copy":"{PRICE} Lock Price Now!","section":"heading"},
        {"particular":"H3","copy":"Live Grand in {CITY}","section":"heading"},

        {"particular":"Description 1 (A)","copy":"{BUILDER + PROJECT} - Luxe Apartments From {PRICE}. Lock Price Now! Limited Units","section":"description"},
        {"particular":"Description 1 (B)","copy":"{PROJECT} {CITY} {TYPOLOGY 1} BHK starts {PRICE}. Exclusive Deal! Filling Fast.","section":"description"},
        {"particular":"Description 2 (A)","copy":"Book Your Dream Apartments Today - Premium Living Awaits!","section":"description"},
        {"particular":"Description 2 (B)","copy":"Luxury Apartments in Prime Location - Schedule a Site Visit Now!","section":"description"},
        {"particular":"Description 3","copy":"{PROJECT} Offers {JOIN:TYPOLOGY 1, TYPOLOGY 2, TYPOLOGY 3, TYPOLOGY 4, TYPOLOGY 5, TYPOLOGY 6} BHK Apartments in {ROAD} Project Starting From {PRICE} Onwards","section":"description","X": true},
        {"particular":"Description 4","copy":"{BUILDER + PROJECT}: Modern Design, Premium Amenities & Prime Location for Elevated Living","section":"description"},
        {"particular":"Description 5","copy":"{BUILDER + PROJECT} - for Greener View, Greater Connectivity & Worldclass Amenities","section":"description"},
        {"particular":"Description 6","copy":"This Project Embodies Modern Urban Living, Offering Residents a Blend of Comfort and Convenience","section":"description"},
        {"particular":"Description 7","copy":"{BUILDER + PROJECT} is a Proposed Luxury Residential Development on {ROAD} in {SECTOR}, {CITY}","section":"description"},
        {"particular":"Description 8","copy":"Buy Your Premium Homes, It is Offering Opulent {JOIN:TYPOLOGY 1, TYPOLOGY 2, TYPOLOGY 3, TYPOLOGY 4, TYPOLOGY 5, TYPOLOGY 6} BHK Apartments With Contemporary Facilities","section":"description","X": true},
        {"particular":"Description 9","copy":"Experience Riverside Living at {PROJECT}, {CITY} {LOCATION} – Now Launching","section":"description"},
        {"particular":"Description 10","copy":"Bookings Open {PROJECT} {JOIN:TYPOLOGY 1, TYPOLOGY 2, TYPOLOGY 3, TYPOLOGY 4, TYPOLOGY 5, TYPOLOGY 6} BHK Start at {PRICE}. Ask Expert & Visit Site","section":"description","X": true},
        {"particular":"Description 11","copy":"Your Mornings Begin by the Water’s Edge and Evenings Slow Down Under the Open Sky","section":"description"},
        {"particular":"Description 12","copy":"Emphasizes a Blend of Urban Convenience and Natural Charm, Featuring a Large Riverside Apartments","section":"description"},
        {"particular":"Description 13","copy":"RERA Approved - Limited {JOIN:TYPOLOGY 1, TYPOLOGY 2, TYPOLOGY 3, TYPOLOGY 4, TYPOLOGY 5, TYPOLOGY 6} BHK Starts {PRICE}. Pre-book for exclusive launch","section":"description","X": true},
        {"particular":"Description 14","copy":"Introducing {PROJECT} in {ROAD}, {LOCATION}. Premium {JOIN:TYPOLOGY 1, TYPOLOGY 2, TYPOLOGY 3, TYPOLOGY 4, TYPOLOGY 5, TYPOLOGY 6} BHK Start {PRICE}","section":"description"},
        {"particular":"Description 15","copy":"{PROJECT} is an upcoming luxury residential project located in {CITY} on {ROAD}","section":"description"},
        {"particular":"Description 16","copy":"{PROJECT} {CITY} is an integrated development nestled in the lap of nature","section":"description"},
        {"particular":"Description 17","copy":"Booking open for limited time only, sign up & get instant call back now. Early buy discount.","section":"description"},
        {"particular":"Description 18","copy":"{PROJECT} {CITY} offers luxury {JOIN:TYPOLOGY 1, TYPOLOGY 2, TYPOLOGY 3, TYPOLOGY 4, TYPOLOGY 5, TYPOLOGY 6} BHK with top amenities and privacy-first layouts.","section":"description","X": true},
        {"particular":"Description 19","copy":"Explore this {TYPOLOGY 1} BHK Apartment in {CITY} to buy or invest in {LOCATION}","section":"description"},
        {"particular":"Description 20","copy":"{PROJECT}, {JOIN:TYPOLOGY 1, TYPOLOGY 2, TYPOLOGY 3, TYPOLOGY 4, TYPOLOGY 5, TYPOLOGY 6} BHK Apartments, at {CITY} {LOCATION}. No Hidden Charges. Site Visit.","section":"description","X": true}
      ],
      "variables": [
        "BUILDER + PROJECT","LOCATION","TYPOLOGY 1","TYPOLOGY 2","TYPOLOGY 3","TYPOLOGY 4",
        "TYPOLOGY 5","TYPOLOGY 6","PROJECT","CITY","PRICE","PRICE RANGE","ROAD","SECTOR"
      ],
      "samples": {
        "Builder + Project": "godrej ananda",
        "Location": "bangalore",
        "Typology 1": "1",
        "Typology 2": "2",
        "Typology 3": "3",
        "Typology 4": "4",
        "Typology 5": "5",
        "Typology 6": "6",
        "Project": "ananda",
        "City": "yelahanka",
        "Price": "₹1.187Cr*",
        "Price Range": "₹1.87 - 3.03Cr*",
        "Road": "sarjapur road",
        "Sector": "sector 104"
      }
    },

    "Type 2": {
      "nickname": "Brand_Plots",
      "columns": ["Campaign Name", "Adset Name", "Keywords"],
      "searchRows": [
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}","keywords":"{BUILDER + PROJECT}"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}","keywords":"{BUILDER + PROJECT} {LOCATION}"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_plots","keywords":"{BUILDER + PROJECT} plots"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_amenities","keywords":"{BUILDER + PROJECT} amenities"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_best_offers","keywords":"{BUILDER + PROJECT} best offers"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_booking","keywords":"{BUILDER + PROJECT} booking"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_construction_status","keywords":"{BUILDER + PROJECT} construction status"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_launch_price","keywords":"{BUILDER + PROJECT} launch price"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_launch_date","keywords":"{BUILDER + PROJECT} launch date"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_location","keywords":"{BUILDER + PROJECT} location"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_master_plan","keywords":"{BUILDER + PROJECT} master plan"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_payment_plan","keywords":"{BUILDER + PROJECT} payment plan"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_possession_date","keywords":"{BUILDER + PROJECT} possession date"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_price","keywords":"{BUILDER + PROJECT} price"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_rera_number","keywords":"{BUILDER + PROJECT} rera number"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_reviews","keywords":"{BUILDER + PROJECT} reviews"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_site_visit","keywords":"{BUILDER + PROJECT} site visit"},
        {"campaign":"BRAND_{BUILDER + PROJECT}_search","adset":"{BUILDER + PROJECT}_specifications","keywords":"{BUILDER + PROJECT} specifications"}
      ],
      "adsColumns": ["Particulars", "Ads Copy"],
      "adsRows": [
        {"particular":"H1 - Project Name","copy":"{BUILDER + PROJECT}","section":"heading"},
        {"particular":"H1 - Location","copy":"{BUILDER + PROJECT} {CITY}","section":"heading"},
        {"particular":"H1 - Project type","copy":"Premium Residential {TYPOLOGY 1}","section":"heading"},
        {"particular":"H1 - Project + Location","copy":"{PROJECT} {LOCATION}","section":"heading"},
        {"particular":"1 - Project + Luxury + Type","copy":"{PROJECT} {TYPOLOGY 1}","section":"heading"},
        {"particular":"1 - Project + Location + City","copy":"{PROJECT} {CITY}","section":"heading"},
        {"particular":"2 - Price Range","copy":"Price {PRICE RANGE}","section":"heading"},
        {"particular":"2 - Starting Price","copy":"Price Starts {PRICE}","section":"heading"},
        {"particular":"2 - Type & Starting Price","copy":"{TYPOLOGY 1} Starts {PRICE}","section":"heading"},
        {"particular":"H3","copy":"Lock Price Now!","section":"heading"},
        {"particular":"H3","copy":"Exclusive Deal","section":"heading"},
        {"particular":"H3","copy":"Filling Fast","section":"heading"},
        {"particular":"H3","copy":"Hold Price","section":"heading"},
        {"particular":"H3","copy":"Limited Units","section":"heading"},
        {"particular":"H3","copy":"Experience A Modern Living","section":"heading"},
        {"particular":"H3","copy":"Avail Pre-Launch Offers","section":"heading"},
        {"particular":"H3","copy":"Get In Touch With Us","section":"heading"},
        {"particular":"H3","copy":"View Prices, Deals & Offers","section":"heading"},
        {"particular":"H3","copy":"Pre-Launch Offers Live Now","section":"heading"},
        {"particular":"H3","copy":"Get Instant Call Back","section":"heading"},
        {"particular":"H3","copy":"{PRICE} Lock Price Now!","section":"heading"},
        {"particular":"H3","copy":"Live Grand in {CITY}","section":"heading"},

        {"particular":"Description 1 (A)","copy":"Explore a Stunning Collection of Premium {TYPOLOGY 1} at {PROJECT} at ₹ {PRICE} Visit Today","section":"description"},
        {"particular":"Description 1 (B)","copy":"{PROJECT} {TYPOLOGY 1} High Return on Investment and Appreciation at {CITY} With Eoi Benefits Open","section":"description"},
        {"particular":"Description 2 (A)","copy":"Premium Plots at {PROJECT} {LOCATION} – {ACRE} Project With Clubhouse & worldclass Amenities","section":"description"},
        {"particular":"Description 2 (B)","copy":"Welcome to New Launch {BUILDER + PROJECT}, Get Official Price List, Floor Plans & Offers","section":"description"},
        {"particular":"Description 3","copy":"Book Your Plot at {PROJECT} {CITY} Today & Begin Your Journey of a Lifetime","section":"description"},
        {"particular":"Description 4","copy":"{BUILDER + PROJECT} Township {CITY} {LOCATION}, Offers Luxurious {TYPOLOGY 1}, From ₹ {PRICE}","section":"description"},
        {"particular":"Description 5","copy":"{BUILDER + PROJECT} offers an Unmatched Blend Of Luxury, Comfort, And Convenience in {LOCATION}","section":"description"},
        {"particular":"Description 6","copy":"{BUILDER + PROJECT} {CITY} Ensuring a Perfect Balance Of Modern Living And Nature’s Tranquility","section":"description"},
        {"particular":"Description 7","copy":"Now. Get Discount on Booking. Schedule Your Free Site Visit & Get Complete Project Details","section":"description"},
        {"particular":"Description 8","copy":"Premium Plots in {CITY}, Designed for a Luxurious Lifestyle With Modern Infrastructure","section":"description"},
        {"particular":"Description 9","copy":"Impending Premium Plotted Project. This Property is Providing {TYPOLOGY 1} With Ultra-modern Niceties","section":"description"},
        {"particular":"Description 10","copy":"Buy Premium Residential {TYPOLOGY 1} Start at {PRICE} Onwards at {CITY} + {LOCATION} Book Now","section":"description"}
      ],
      "variables": [
        "BUILDER + PROJECT","LOCATION","TYPOLOGY 1","TYPOLOGY 2","TYPOLOGY 3","TYPOLOGY 4",
        "TYPOLOGY 5","TYPOLOGY 6","PROJECT","CITY","PRICE","PRICE RANGE","ROAD","SECTOR","ACRE"
      ],
      "samples": {
        "BUILDER + PROJECT": "godrej ananda",
        "LOCATION": "bangalore",
        "TYPOLOGY 1": "1",
        "TYPOLOGY 2": "2",
        "TYPOLOGY 3": "3",
        "TYPOLOGY 4": "4",
        "TYPOLOGY 5": "5",
        "TYPOLOGY 6": "6",
        "PROJECT": "ananda",
        "CITY": "Yelahanka",
        "PRICE": "Rs.1.187Cr*",
        "PRICE RANGE": "Rs.1.87 - 3.03Cr*",
        "ROAD": "sarjapur road",
        "SECTOR": "sector 104",
        "ACRE": "3"
      }
    }
  }
};
